- hosts: localhost
  become: no

  vars:
    packages: "wget"

  tasks:
  - name: Install gantsign.oh-my-zsh role from Ansible Galaxy
    community.general.ansible_galaxy_install:
      type: role
      name: gantsign.oh-my-zsh

  - name: Install zsh
    when: ansible_distribution != "MacOSX"
    become: yes
    package:
      name: "zsh"
      state: present

  - name: Install packages
    when: ansible_distribution != "MacOSX"
    become: yes
    package:
      name: "{{ packages }}"
      state: present

  - name: Install packages (macOS)
    when: ansible_distribution == "MacOSX"
    package:
      name: "{{ packages }}"
      state: present

  - name: Install eza [1/4] - Install gpg (Debian/Ubuntu)
    become: yes
    when: ansible_distribution_file_variety == "Debian"
    package:
      name: gpg
      state: present
  - name: Install eza [2/4] - Create keyrings folder (Debian/Ubuntu)
    become: yes
    when: ansible_distribution_file_variety == "Debian"
    file:
      path: /etc/apt/keyrings/
      state: directory
  - name: Install eza [3/4] - Add GPG key (Debian/Ubuntu)
    become: yes
    when: ansible_distribution_file_variety == "Debian"
    apt_key:
      url: https://raw.githubusercontent.com/eza-community/eza/main/deb.asc
      keyring: /etc/apt/keyrings/gierens.gpg
      state: present
  - name: Install eza [4/4] - Add eza repo (Debian/Ubuntu)
    become: yes
    when: ansible_distribution_file_variety == "Debian"
    apt_repository:
      repo: deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main
      state: present

  - name: Install eza
    when: ansible_distribution != "MacOSX"
    become: yes
    package:
      name: eza
      state: present
      update_cache: yes
      
  - name: Install eza (macOS)
    when: ansible_distribution == "MacOSX"
    package:
      name: eza
      state: present

  - name: Configure Oh My Zsh for {{ ansible_user_id }}
    include_role:
      name: gantsign.oh-my-zsh
    vars:
      oh_my_zsh_update_mode: auto
      oh_my_zsh_update_frequency: 14
      users:
        - username: "{{ ansible_user_id }}"
          oh_my_zsh:
            theme: alanpeabody
            plugins:
              - git
              - timer
              - zsh-autosuggestions
              - zsh-syntax-highlighting
              - kubectl

  - name: Clone zsh-autosuggestions
    git:
      repo: https://github.com/zsh-users/zsh-autosuggestions.git
      dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  - name: Clone zsh-syntax-highlighting
    git:
      repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"

  - name: Clone dotfiles
    git:
      repo: "https://github.com/Xelofan/dotfiles"
      dest: '~/dotfiles'

  - name: Add block to zshrc
    blockinfile:
      path: "~/.zshrc"
      block: |
        source ~/dotfiles/main.sh
