- hosts: all
  become: true

  vars:
    address_pool: "172.22.0.0/24"
    vip: "10.0.0.70"

    brick_dir: "/glusterfs/brick1"
    mount_dir: /mnt
    volume_name: "gluster-volume"
    hosts: "{{ ansible_play_hosts }}"
    replicasNo: "{{ hosts | length }}"

  tasks:
  - name: Include GlusterFS tasks
    import_tasks: tasks/glusterfs.yml
  
  - name: Include Swarm deployment tasks
    import_tasks: tasks/swarm.yml
