- name: Install glusterfs-server
  package:
    name: "glusterfs-server,software-properties-common"
    state: latest

- name: Enable & start glusterd
  systemd_service:
    name: glusterd
    state: started
    enabled: true

- name: Create brick directory
  file:
    path: "{{ brick_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create pool
  gluster.gluster.gluster_peer:
    state: present
    nodes: "{{ hosts }}"

- name: Create GlusterFS cluster
  run_once: true
  gluster.gluster.gluster_volume:
    state: present
    name: "{{ volume_name }}"
    bricks: "{{ brick_dir }}"
    replicas: "{{ replicasNo }}"
    cluster: "{{ hosts }}"
    host: "{{ inventory_hostname }}"
    force: true
    start_on_create: true

- name: Change mandatory locks to optimal
  run_once: true
  gluster.gluster.gluster_volume:
    state: present
    name: "{{ volume_name }}"
    options:
      locks.mandatory-locking: "optimal"

- name: Mount gluster volume
  mount:
    name: "{{ mount_dir }}"
    src: "{{ inventory_hostname }}:/{{ volume_name }}"
    fstype: glusterfs
    state: mounted

- name: Mount at boot too
  mount:
    name: "{{ mount_dir }}"
    src: "{{ inventory_hostname }}:{{ volume_name }}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: present
