- hosts: localhost
  become: yes

  vars_prompt:
    - name: usertoadd
      prompt: "Specify a user's name to add them to 'docker' group (leave blank to skip this)"
      private: no

  tasks:

  - name: Install required system packages
    package:
      name:
        - ca-certificates
        - curl
        - gnupg
      state: latest
      update_cache: yes

  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/'{{ ansible_distribution | lower }}'/gpg
      state: present  - name: Set up repository (2/3) - Add Docker's GPG key

  - name: Add Docker repository
    apt_repository:
      repo: deb https://download.docker.com/linux/'{{ ansible_distribution | lower }}' {{ ansible_distribution_release }} stable
      state: present

  - name: Install Docker
    package:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: latest
      update_cache: yes
    
  - name: Start & enable Docker
    systemd:
      name: docker.service
      state: started
      enabled: yes

  - name: Add specified user to docker group ('{{ usertoadd }}')
    when: usertoadd
    user:
      name: '{{ usertoadd }}'
      groups: docker
      append: yes